// @ts-nocheck
const MATCHES = [
  [
    'Real Madrid',
    'Barcelona',
    'LaLiga',
    'scheduled',
    '1',
    55,
    24,
    21,
    '2 - 1',
    58,
    62,
    82,
    1.8,
    3.4,
    4.5,
    4,
    30,
  ],
  [
    'Manchester City',
    'Arsenal',
    'Premier League',
    'scheduled',
    '1',
    48,
    28,
    24,
    '2 - 1',
    55,
    58,
    78,
    1.95,
    3.5,
    3.8,
    5,
    35,
  ],
  [
    'Bayern Munich',
    'Borussia Dortmund',
    'Bundesliga',
    'scheduled',
    '1',
    52,
    26,
    22,
    '2 - 1',
    60,
    55,
    80,
    1.7,
    4.0,
    4.2,
    6,
    25,
  ],
  [
    'PSG',
    'Marseille',
    'Ligue 1',
    'scheduled',
    '1',
    50,
    28,
    22,
    '2 - 1',
    55,
    52,
    76,
    1.85,
    3.6,
    4.0,
    7,
    30,
  ],
  [
    'Juventus',
    'AC Milan',
    'Serie A',
    'scheduled',
    'X',
    34,
    40,
    26,
    '1 - 1',
    42,
    48,
    72,
    2.4,
    3.2,
    3.1,
    3,
    35,
  ],
  [
    'Liverpool',
    'Chelsea',
    'Premier League',
    'scheduled',
    '1',
    46,
    30,
    24,
    '2 - 1',
    52,
    55,
    74,
    2.0,
    3.4,
    3.7,
    28,
    30,
  ],
  [
    'Inter Milan',
    'Napoli',
    'Serie A',
    'scheduled',
    'X',
    33,
    38,
    29,
    '1 - 1',
    40,
    45,
    70,
    2.5,
    3.15,
    2.95,
    30,
    40,
  ],
  [
    'Barcelona',
    'Atletico Madrid',
    'LaLiga',
    'scheduled',
    '1',
    47,
    28,
    25,
    '2 - 1',
    50,
    52,
    75,
    1.9,
    3.5,
    4.0,
    29,
    30,
  ],
  [
    'Ajax',
    'Feyenoord',
    'Eredivisie',
    'scheduled',
    '1',
    44,
    28,
    28,
    '2 - 1',
    55,
    50,
    71,
    2.1,
    3.5,
    3.3,
    31,
    35,
  ],
  [
    'Benfica',
    'Porto',
    'Liga Portugal',
    'scheduled',
    'X',
    35,
    38,
    27,
    '1 - 1',
    42,
    46,
    69,
    2.45,
    3.2,
    3.0,
    32,
    40,
  ],
  [
    'Lyon',
    'Lille',
    'Ligue 1',
    'live',
    '1',
    52,
    25,
    23,
    '2 - 1',
    62,
    65,
    79,
    1.75,
    3.8,
    4.5,
    -1,
    25,
  ],
  [
    'Roma',
    'Lazio',
    'Serie A',
    'live',
    'X',
    32,
    42,
    26,
    '1 - 1',
    35,
    40,
    73,
    2.6,
    3.1,
    2.85,
    -2,
    45,
  ],
  [
    'Monaco',
    'Rennes',
    'Ligue 1',
    'FT',
    '1',
    55,
    24,
    21,
    '2 - 0',
    55,
    48,
    85,
    1.85,
    3.6,
    3.9,
    -12,
    20,
  ],
  [
    'Wydad Casablanca',
    'Raja Casablanca',
    'Botola Pro',
    'scheduled',
    'X',
    33,
    38,
    29,
    '1 - 1',
    42,
    46,
    70,
    2.6,
    3.1,
    2.8,
    33,
    35,
  ],
  [
    'FAR Rabat',
    'Renaissance Berkane',
    'Botola Pro',
    'scheduled',
    '1',
    44,
    30,
    26,
    '1 - 0',
    38,
    44,
    68,
    2.2,
    3.2,
    3.3,
    34,
    30,
  ],
  [
    'FUS Rabat',
    'Hassania Agadir',
    'Botola Pro',
    'scheduled',
    '1',
    42,
    32,
    26,
    '1 - 0',
    40,
    43,
    65,
    2.3,
    3.15,
    3.2,
    35,
    32,
  ],
  [
    'Al Ahly',
    'Zamalek',
    'Egyptian Premier League',
    'scheduled',
    '1',
    48,
    30,
    22,
    '2 - 1',
    50,
    52,
    75,
    1.8,
    3.4,
    4.2,
    36,
    35,
  ],
  [
    'Esperance Tunis',
    'Club Africain',
    'Ligue 1 Tunisia',
    'scheduled',
    '1',
    44,
    32,
    24,
    '1 - 0',
    42,
    48,
    72,
    2.1,
    3.2,
    3.5,
    37,
    30,
  ],
  [
    'MC Alger',
    'JS Kabylie',
    'Ligue 1 Algeria',
    'scheduled',
    'X',
    34,
    38,
    28,
    '1 - 1',
    40,
    44,
    68,
    2.5,
    3.1,
    2.9,
    38,
    32,
  ],
]

const HOUR = 3600

function buildMatch(row) {
  const [
    home,
    away,
    league,
    status,
    prediction,
    hP,
    dP,
    aP,
    expected,
    ou25,
    btts,
    conf,
    oH,
    oD,
    oA,
    offsetHours,
    chaos,
  ] = row
  const now = Math.floor(Date.now() / 1000)
  const ts = now + offsetHours * HOUR
  return {
    id: `seed_${home.replace(/\s/g, '')}_${away.replace(/\s/g, '')}`,
    homeTeam: home,
    awayTeam: away,
    league,
    status,
    scoreHome: 0,
    scoreAway: 0,
    prediction,
    confidence: conf,
    home_win_probability: hP,
    draw_probability: dP,
    away_win_probability: aP,
    expected_score: expected,
    ou_25_prob: ou25,
    btts_prob: btts,
    xgboost_confidence: conf / 100,
    odds_home: oH,
    odds_draw: oD,
    odds_away: oA,
    startTimestamp: ts,
    timestamp: new Date(ts * 1000).toISOString(),
    source: 'seed',
    chaos_score: chaos || 50,
    insufficient_data: 0,
    last_updated: Date.now(),
  }
}

async function seedDemoMatches(database) {
  let count = 0
  const matches = MATCHES.map(buildMatch)
  for (const m of matches) {
    try {
      await database.insertMatch(m)
      count++
    } catch (_) {}
  }
  return count
}

if (require.main === module) {
  import path from 'path'
  import fs from 'fs'
  const dbPath = path.resolve(__dirname, '..', 'data', 'tactical.db')
  if (fs.existsSync(dbPath)) {
    fs.unlinkSync(dbPath)
    console.log('Deleted old tactical.db')
  }
  import Database from 'better-sqlite3'
  const db = new Database(dbPath)
  db.pragma('journal_mode = WAL')
  db.pragma('foreign_keys = ON')
  db.exec(`
    CREATE TABLE IF NOT EXISTS matches (
      id TEXT PRIMARY KEY, homeTeam TEXT, awayTeam TEXT, league TEXT,
      scoreHome INTEGER DEFAULT 0, scoreAway INTEGER DEFAULT 0, minute TEXT,
      status TEXT, prediction TEXT, confidence REAL, fullData TEXT,
      timestamp TEXT, startTimestamp INTEGER, source TEXT, last_updated INTEGER,
      home_win_probability REAL, draw_probability REAL, away_win_probability REAL,
      expected_score TEXT, chaos_score INTEGER, ou_25_prob REAL, btts_prob REAL,
      xgboost_confidence REAL, odds_home REAL, odds_draw REAL, odds_away REAL
    )
  `)
  const insert = db.prepare(`
    INSERT OR REPLACE INTO matches
    (id, homeTeam, awayTeam, league, status, prediction, confidence,
     home_win_probability, draw_probability, away_win_probability,
     expected_score, ou_25_prob, btts_prob, xgboost_confidence,
     odds_home, odds_draw, odds_away, startTimestamp, timestamp, source,
     chaos_score, insufficient_data, last_updated)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `)
  const matches = MATCHES.map(buildMatch)
  for (const m of matches) {
    insert.run(
      m.id,
      m.homeTeam,
      m.awayTeam,
      m.league,
      m.status,
      m.prediction,
      m.confidence,
      m.home_win_probability,
      m.draw_probability,
      m.away_win_probability,
      m.expected_score,
      m.ou_25_prob,
      m.btts_prob,
      m.xgboost_confidence,
      m.odds_home,
      m.odds_draw,
      m.odds_away,
      m.startTimestamp,
      m.timestamp,
      m.source,
      m.chaos_score,
      m.insufficient_data,
      m.last_updated
    )
  }
  db.exec('CREATE INDEX IF NOT EXISTS idx_matches_status ON matches(status)')
  db.exec('CREATE INDEX IF NOT EXISTS idx_matches_timestamp ON matches(timestamp)')
  console.log(`Seeded ${matches.length} matches`)
  db.close()
}

export = { seedDemoMatches }
