-- Schéma de référence du master dataset produit par data_pipeline.
-- La table est recréée automatiquement par build/store.py à partir du
-- DataFrame ; ce fichier documente la structure pour les consommateurs
-- (ex. scripts/train_xgboost.py) et initialise la base au premier run.

CREATE TABLE IF NOT EXISTS master_matches (
    date             TEXT,
    league           TEXT,
    season           TEXT,
    home_team        TEXT,
    away_team        TEXT,
    fthg             REAL,
    ftag             REAL,
    ftr              TEXT,
    hthg             REAL,
    htag             REAL,
    htr              TEXT,
    hs               REAL,
    away_shots       REAL,
    hst              REAL,
    ast              REAL,
    hc               REAL,
    ac               REAL,
    hy               REAL,
    ay               REAL,
    hr               REAL,
    ar               REAL,
    odds_h_b365      REAL,
    odds_d_b365      REAL,
    odds_a_b365      REAL,
    odds_h_avg       REAL,
    odds_d_avg       REAL,
    odds_a_avg       REAL,
    elo_home         REAL,
    elo_away         REAL,
    home_xg          REAL,
    away_xg          REAL,
    home_xa          REAL,
    away_xa          REAL,
    home_goals       REAL,
    away_goals       REAL,
    H_xg_L5          REAL,
    H_xg_L10         REAL,
    A_xg_L5          REAL,
    A_xg_L10         REAL,
    H_xga_L5         REAL,
    H_xga_L10        REAL,
    A_xga_L5         REAL,
    A_xga_L10        REAL,
    H_xa_L5          REAL,
    H_xa_L10         REAL,
    A_xa_L5          REAL,
    A_xa_L10         REAL,
    H_gf_L5          REAL,
    H_gf_L10         REAL,
    A_gf_L5          REAL,
    A_gf_L10         REAL,
    H_ga_L5          REAL,
    H_ga_L10         REAL,
    A_ga_L5          REAL,
    A_ga_L10         REAL,
    H_pts_L5         REAL,
    H_pts_L10        REAL,
    A_pts_L5         REAL,
    A_pts_L10        REAL,
    F_Elo_Diff       REAL,
    Total_xG_L5      REAL,
    Form_Diff_L5     REAL
);

CREATE INDEX IF NOT EXISTS idx_master_date ON master_matches (date);
CREATE INDEX IF NOT EXISTS idx_master_teams ON master_matches (home_team, away_team);
